/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PDA;

import java.awt.Color;
//import multicast_try.PdaMulti.UnicastThread;

/**
 * This class creates a thread and starts it This class is used to start the
 * Train Server.
 *
 * @author Mikael Kofod, Sune Heide
 */
public class PdaGui extends javax.swing.JFrame {

    PdaMulti pdaThread;
    PdaUni unicasterThread;
    volatile boolean startThread;

    /**
     * Creates new form PdaGui The constructior initializes the components and
     * ensures the correct windows are opened at the start.
     */
    public PdaGui() {
        initComponents();
        pdaStartWindow();
    }

    /**
     * This method creates and starts a thread and requires a username and
     * password
     *
     * @param username
     * @param password
     */
    public void startMulticaster(String username, String password) {
        pdaThread = new PdaMulti(this, username, password, unicasterThread);
        pdaThread.start();
    }

    public void startUnicaster(String username) {
        unicasterThread = new PdaUni(this, username);
        unicasterThread.start();

    }

    public void interruptThreads() {
        pdaThread.interrupt();
        unicasterThread.interrupt();
    }

    /**
     * This method makes the correct panel visible at the start of the program.
     */
    public void pdaStartWindow() {
        pdaLoginPanel.setVisible(true);
        pdaLogoutPanel.setVisible(false);
        pdaColorPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pdaLoginPanel = new javax.swing.JPanel();
        pdaUsernameTextField = new javax.swing.JTextField();
        pdaPasswordTextField = new javax.swing.JTextField();
        pdaLoginBtn = new javax.swing.JButton();
        pdaUsernameLabel = new javax.swing.JLabel();
        pdaPasswordLabel = new javax.swing.JLabel();
        pdaLogoutPanel = new javax.swing.JPanel();
        pdaLogoutBtn = new javax.swing.JButton();
        pdaColorPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pdaLoginBtn.setText("Login");
        pdaLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdaLoginBtnActionPerformed(evt);
            }
        });

        pdaUsernameLabel.setText("Username");

        pdaPasswordLabel.setText("Password");

        javax.swing.GroupLayout pdaLoginPanelLayout = new javax.swing.GroupLayout(pdaLoginPanel);
        pdaLoginPanel.setLayout(pdaLoginPanelLayout);
        pdaLoginPanelLayout.setHorizontalGroup(
            pdaLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdaLoginPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(pdaLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pdaLoginPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pdaLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pdaUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdaUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(pdaLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pdaPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdaPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        pdaLoginPanelLayout.setVerticalGroup(
            pdaLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdaLoginPanelLayout.createSequentialGroup()
                .addGroup(pdaLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdaUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdaPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pdaLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdaUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdaPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pdaLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pdaLogoutBtn.setText("Logout");
        pdaLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdaLogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pdaColorPanelLayout = new javax.swing.GroupLayout(pdaColorPanel);
        pdaColorPanel.setLayout(pdaColorPanelLayout);
        pdaColorPanelLayout.setHorizontalGroup(
            pdaColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pdaColorPanelLayout.setVerticalGroup(
            pdaColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pdaLogoutPanelLayout = new javax.swing.GroupLayout(pdaLogoutPanel);
        pdaLogoutPanel.setLayout(pdaLogoutPanelLayout);
        pdaLogoutPanelLayout.setHorizontalGroup(
            pdaLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdaLogoutPanelLayout.createSequentialGroup()
                .addGroup(pdaLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pdaLogoutPanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(pdaLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pdaLogoutPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(pdaColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pdaLogoutPanelLayout.setVerticalGroup(
            pdaLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdaLogoutPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(pdaLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(pdaColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pdaLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(pdaLogoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pdaLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pdaLogoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method changes which panels are currently showed, changes the color
     * of another panel and calls the method that creates the thread.
     *
     * @param evt
     */
    private void pdaLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdaLoginBtnActionPerformed
        pdaLoginPanel.setVisible(false);
        pdaLogoutPanel.setVisible(true);
        pdaColorPanel.setVisible(true);

        pdaColorPanel.setBackground(Color.BLUE);

        startThread = true;

        startUnicaster(pdaUsernameTextField.getText());
        startMulticaster(pdaUsernameTextField.getText(), pdaPasswordTextField.getText());



    }//GEN-LAST:event_pdaLoginBtnActionPerformed

    /**
     * This method changes which panels are currently shows and sets the boolean
     * value of startThread to false which ends the while loop in the thread.
     *
     * @param evt
     */
    private void pdaLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdaLogoutBtnActionPerformed
        pdaLoginPanel.setVisible(true);
        pdaLogoutPanel.setVisible(false);
        pdaColorPanel.setVisible(true);

        interruptThreads();
        startThread = false;

    }//GEN-LAST:event_pdaLogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PdaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PdaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PdaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PdaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PdaGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel pdaColorPanel;
    private javax.swing.JButton pdaLoginBtn;
    private javax.swing.JPanel pdaLoginPanel;
    private javax.swing.JButton pdaLogoutBtn;
    private javax.swing.JPanel pdaLogoutPanel;
    private javax.swing.JLabel pdaPasswordLabel;
    public javax.swing.JTextField pdaPasswordTextField;
    private javax.swing.JLabel pdaUsernameLabel;
    public javax.swing.JTextField pdaUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
